@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

@name = LINKS ROUTES
### Create Link
POST http://{{host}}/api/links
Content-Type: {{contentType}}

{
  "url": "https://vitest.dev/api/expect#not"
}

### Visit Link
GET http://{{host}}/ee7214 



####################### SEPARA ROTAS 
@name = USERS ROUTES

### Create User
POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
  "name": "Gabriel Carniel",
  "email": "gabriel@fakeemail.com",
  "password": "123456"
}