@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNzkwMWNiNS1kNWY5LTQ5NGMtOTMyMy1hMGJmYzk5YTJhMjMiLCJpYXQiOjE3MTEyMTEzMDh9.KR9tMpInmbDJw7SVoYmysuxoUzt0efajo4abvpeCLNM

@name = LINKS ROUTES
### Create Link
POST http://{{host}}/api/links
Content-Type: {{contentType}}
Authorization: Bearer {{bearer}}

{
  "url": "https://github.com/Huachao/vscode-restclient"
}

### Visit Link
GET http://{{host}}/ee7214 

### List links by user
GET http://{{host}}/api/links?page=1&pageSize=10
Authorization: Bearer {{bearer}}




####################### SEPARA ROTAS ####################### 
@name = USERS ROUTES

### Create User
POST http://{{host}}/api/users
Content-Type: {{contentType}}

{
  "name": "Gabriel Carniel",
  "email": "gabriel@fakeemail.com",
  "password": "123456"
}

### Authenticate User
POST http://{{host}}/api/auth
Content-Type: {{contentType}}

{
  "email": "gabriel@fakeemail.com",
  "password": "123456"
}